name: row_row_row
description: A command-line tool to generate Dart models for Supabase table rows based on the OpenAPI spec.
version: 0.1.0
repository: https://github.com/ianbucal/row_row_row
homepage: https://github.com/ianbucal/row_row_row
issue_tracker: https://github.com/ianbucal/row_row_row/issues

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.5.0 # Use latest compatible version
  dotenv: ^4.2.0 # Use latest compatible version
  http: ^1.2.1 # Use latest compatible version

dev_dependencies:
  lints: ^4.0.0 # Use latest compatible version
  test: ^1.25.2 # Use latest compatible version

executables:
  row_row_row: # Leave as is, or rename if desired for global activation

# Optional: Add topics for pub.dev discovery
topics:
  - supabase
  - code-generation
  - dart
  - cli