name: row_row_row
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.4.0
  dotenv: ^4.0.1
  http: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  row_row_row: bin/row_row_row.dart