// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class AnnouncementSeenRow {
  static const table = 'announcement_seen';

  static const field = (
    id: 'id',
    seenAt: 'seen_at',
    expectedSeenBy: 'expected_seen_by',
    createdAt: 'created_at',
    announcement: 'announcement',
    deletedAt: 'deleted_at',
  );

  final String id;
  final DateTime? seenAt;
  final String expectedSeenBy;
  final DateTime createdAt;
  final String announcement;
  final DateTime? deletedAt;

  const AnnouncementSeenRow({
    required this.id,
    this.seenAt,
    required this.expectedSeenBy,
    required this.createdAt,
    required this.announcement,
    this.deletedAt,
  });

  factory AnnouncementSeenRow.fromJson(Map<String, dynamic> json) {
    return AnnouncementSeenRow(
      id: json[field.id] as String,
      seenAt: json[field.seenAt] == null ? null : DateTime.tryParse(json[field.seenAt] ?? ''),
      expectedSeenBy: json[field.expectedSeenBy] as String,
      createdAt: DateTime.parse(json[field.createdAt]),
      announcement: json[field.announcement] as String,
      deletedAt: json[field.deletedAt] == null ? null : DateTime.tryParse(json[field.deletedAt] ?? ''),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.seenAt: seenAt?.toIso8601String(),
      field.expectedSeenBy: expectedSeenBy,
      field.createdAt: createdAt.toIso8601String(),
      field.announcement: announcement,
      field.deletedAt: deletedAt?.toIso8601String(),
    };
  }

  AnnouncementSeenRow copyWith({
    String? id,
    DateTime? seenAt,
    String? expectedSeenBy,
    DateTime? createdAt,
    String? announcement,
    DateTime? deletedAt,
  }) {
    return AnnouncementSeenRow(
      id: id ?? this.id,
      seenAt: seenAt ?? this.seenAt,
      expectedSeenBy: expectedSeenBy ?? this.expectedSeenBy,
      createdAt: createdAt ?? this.createdAt,
      announcement: announcement ?? this.announcement,
      deletedAt: deletedAt ?? this.deletedAt,
    );
  }
}
