// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class AnnouncementRoleRow {
  static const table = 'announcement_role';

  static const field = (
    announcement: 'announcement',
    role: 'role',
    createdAt: 'created_at',
    id: 'id',
  );

  final String? announcement;
  final String? role;
  final DateTime createdAt;
  final String? id;

  const AnnouncementRoleRow({
    this.announcement,
    this.role,
    required this.createdAt,
    this.id,
  });

  factory AnnouncementRoleRow.fromJson(Map<String, dynamic> json) {
    return AnnouncementRoleRow(
      announcement: json[field.announcement],
      role: json[field.role],
      createdAt: DateTime.parse(json[field.createdAt]),
      id: json[field.id],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.announcement: announcement,
      field.role: role,
      field.createdAt: createdAt.toIso8601String(),
      field.id: id,
    };
  }

  AnnouncementRoleRow copyWith({
    String? announcement,
    String? role,
    DateTime? createdAt,
    String? id,
  }) {
    return AnnouncementRoleRow(
      announcement: announcement ?? this.announcement,
      role: role ?? this.role,
      createdAt: createdAt ?? this.createdAt,
      id: id ?? this.id,
    );
  }
}
