// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ChatNumberOfUnseenRow {
  static const table = 'chat_number_of_unseen';

  static const field = (
    chatRoomId: 'chat_room_id',
    memberId: 'member_id',
    lastSeenAt: 'last_seen_at',
    numberOfUnseenMessages: 'number_of_unseen_messages',
  );

  final String? chatRoomId;
  final String? memberId;
  final DateTime? lastSeenAt;
  final int? numberOfUnseenMessages;

  const ChatNumberOfUnseenRow({
    this.chatRoomId,
    this.memberId,
    this.lastSeenAt,
    this.numberOfUnseenMessages,
  });

  factory ChatNumberOfUnseenRow.fromJson(Map<String, dynamic> json) {
    return ChatNumberOfUnseenRow(
      chatRoomId: json[field.chatRoomId],
      memberId: json[field.memberId],
      lastSeenAt: json[field.lastSeenAt] == null ? null : DateTime.tryParse(json[field.lastSeenAt] ?? ''),
      numberOfUnseenMessages: json[field.numberOfUnseenMessages] == null ? null : (json[field.numberOfUnseenMessages] as num?)?.toInt(),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.chatRoomId: chatRoomId,
      field.memberId: memberId,
      field.lastSeenAt: lastSeenAt?.toIso8601String(),
      field.numberOfUnseenMessages: numberOfUnseenMessages,
    };
  }

  ChatNumberOfUnseenRow copyWith({
    String? chatRoomId,
    String? memberId,
    DateTime? lastSeenAt,
    int? numberOfUnseenMessages,
  }) {
    return ChatNumberOfUnseenRow(
      chatRoomId: chatRoomId ?? this.chatRoomId,
      memberId: memberId ?? this.memberId,
      lastSeenAt: lastSeenAt ?? this.lastSeenAt,
      numberOfUnseenMessages: numberOfUnseenMessages ?? this.numberOfUnseenMessages,
    );
  }
}
