// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ChatCategoryRow {
  static const table = 'chat_category';

  static const field = (
    id: 'id',
    name: 'name',
    user: 'user',
    createdAt: 'created_at',
  );

  final String id;
  final String? name;
  final String? user;
  final DateTime createdAt;

  const ChatCategoryRow({
    required this.id,
    this.name,
    this.user,
    required this.createdAt,
  });

  factory ChatCategoryRow.fromJson(Map<String, dynamic> json) {
    return ChatCategoryRow(
      id: json[field.id] as String,
      name: json[field.name],
      user: json[field.user],
      createdAt: DateTime.parse(json[field.createdAt]),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.name: name,
      field.user: user,
      field.createdAt: createdAt.toIso8601String(),
    };
  }

  ChatCategoryRow copyWith({
    String? id,
    String? name,
    String? user,
    DateTime? createdAt,
  }) {
    return ChatCategoryRow(
      id: id ?? this.id,
      name: name ?? this.name,
      user: user ?? this.user,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
