// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ChatRoomMessageTagUserRow {
  static const table = 'chat_room_message_tag_user';

  static const field = (
    id: 'id',
    message: 'message',
    user: 'user',
    createdAt: 'created_at',
    taggedName: 'tagged_name',
  );

  final String id;
  final String? message;
  final String? user;
  final DateTime createdAt;
  final String? taggedName;

  const ChatRoomMessageTagUserRow({
    required this.id,
    this.message,
    this.user,
    required this.createdAt,
    this.taggedName,
  });

  factory ChatRoomMessageTagUserRow.fromJson(Map<String, dynamic> json) {
    return ChatRoomMessageTagUserRow(
      id: json[field.id] as String,
      message: json[field.message],
      user: json[field.user],
      createdAt: DateTime.parse(json[field.createdAt]),
      taggedName: json[field.taggedName],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.message: message,
      field.user: user,
      field.createdAt: createdAt.toIso8601String(),
      field.taggedName: taggedName,
    };
  }

  ChatRoomMessageTagUserRow copyWith({
    String? id,
    String? message,
    String? user,
    DateTime? createdAt,
    String? taggedName,
  }) {
    return ChatRoomMessageTagUserRow(
      id: id ?? this.id,
      message: message ?? this.message,
      user: user ?? this.user,
      createdAt: createdAt ?? this.createdAt,
      taggedName: taggedName ?? this.taggedName,
    );
  }
}
