// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class CountryRow {
  static const table = 'country';

  static const field = (
    iso: 'iso',
    name: 'name',
    nicename: 'nicename',
    iso3: 'iso3',
    numcode: 'numcode',
    phonecode: 'phonecode',
  );

  final String iso;
  final String name;
  final String nicename;
  final String? iso3;
  final int? numcode;
  final int phonecode;

  const CountryRow({
    required this.iso,
    required this.name,
    required this.nicename,
    this.iso3,
    this.numcode,
    required this.phonecode,
  });

  factory CountryRow.fromJson(Map<String, dynamic> json) {
    return CountryRow(
      iso: json[field.iso] as String,
      name: json[field.name] as String,
      nicename: json[field.nicename] as String,
      iso3: json[field.iso3],
      numcode: json[field.numcode] == null ? null : (json[field.numcode] as num?)?.toInt(),
      phonecode: (json[field.phonecode] as num).toInt(),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.iso: iso,
      field.name: name,
      field.nicename: nicename,
      field.iso3: iso3,
      field.numcode: numcode,
      field.phonecode: phonecode,
    };
  }

  CountryRow copyWith({
    String? iso,
    String? name,
    String? nicename,
    String? iso3,
    int? numcode,
    int? phonecode,
  }) {
    return CountryRow(
      iso: iso ?? this.iso,
      name: name ?? this.name,
      nicename: nicename ?? this.nicename,
      iso3: iso3 ?? this.iso3,
      numcode: numcode ?? this.numcode,
      phonecode: phonecode ?? this.phonecode,
    );
  }
}
