// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class DueDateTaskSubtaskAppointmentViewRow {
  static const table = 'due_date_task_subtask_appointment_view';

  static const field = (
    dueDate: 'due_date',
    taskId: 'task_id',
    subtaskId: 'subtask_id',
    taskAppointmentId: 'task_appointment_id',
    source: 'source',
    taskName: 'task_name',
    subtaskName: 'subtask_name',
    appointmentNotes: 'appointment_notes',
    assigneeId: 'assignee_id',
    assigneeName: 'assignee_name',
    taskDetails: 'task_details',
    subtaskDetails: 'subtask_details',
    appointmentDetails: 'appointment_details',
    projectId: 'project_id',
    projectName: 'project_name',
    createdAt: 'created_at',
    taskCollaborators: 'task_collaborators',
  );

  final DateTime? dueDate;
  final String? taskId;
  final String? subtaskId;
  final String? taskAppointmentId;
  final String? source;
  final String? taskName;
  final String? subtaskName;
  final String? appointmentNotes;
  final String? assigneeId;
  final String? assigneeName;
  final String? taskDetails;
  final String? subtaskDetails;
  final String? appointmentDetails;
  final String? projectId;
  final String? projectName;
  final DateTime? createdAt;
  final List<String>? taskCollaborators;

  const DueDateTaskSubtaskAppointmentViewRow({
    this.dueDate,
    this.taskId,
    this.subtaskId,
    this.taskAppointmentId,
    this.source,
    this.taskName,
    this.subtaskName,
    this.appointmentNotes,
    this.assigneeId,
    this.assigneeName,
    this.taskDetails,
    this.subtaskDetails,
    this.appointmentDetails,
    this.projectId,
    this.projectName,
    this.createdAt,
    this.taskCollaborators,
  });

  factory DueDateTaskSubtaskAppointmentViewRow.fromJson(Map<String, dynamic> json) {
    return DueDateTaskSubtaskAppointmentViewRow(
      dueDate: json[field.dueDate] == null ? null : DateTime.tryParse(json[field.dueDate] ?? ''),
      taskId: json[field.taskId],
      subtaskId: json[field.subtaskId],
      taskAppointmentId: json[field.taskAppointmentId],
      source: json[field.source],
      taskName: json[field.taskName],
      subtaskName: json[field.subtaskName],
      appointmentNotes: json[field.appointmentNotes],
      assigneeId: json[field.assigneeId],
      assigneeName: json[field.assigneeName],
      taskDetails: json[field.taskDetails],
      subtaskDetails: json[field.subtaskDetails],
      appointmentDetails: json[field.appointmentDetails],
      projectId: json[field.projectId],
      projectName: json[field.projectName],
      createdAt: json[field.createdAt] == null ? null : DateTime.tryParse(json[field.createdAt] ?? ''),
      taskCollaborators: json[field.taskCollaborators] == null ? null : List<String>.from(json[field.taskCollaborators]),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.dueDate: dueDate?.toIso8601String(),
      field.taskId: taskId,
      field.subtaskId: subtaskId,
      field.taskAppointmentId: taskAppointmentId,
      field.source: source,
      field.taskName: taskName,
      field.subtaskName: subtaskName,
      field.appointmentNotes: appointmentNotes,
      field.assigneeId: assigneeId,
      field.assigneeName: assigneeName,
      field.taskDetails: taskDetails,
      field.subtaskDetails: subtaskDetails,
      field.appointmentDetails: appointmentDetails,
      field.projectId: projectId,
      field.projectName: projectName,
      field.createdAt: createdAt?.toIso8601String(),
      field.taskCollaborators: taskCollaborators,
    };
  }

  DueDateTaskSubtaskAppointmentViewRow copyWith({
    DateTime? dueDate,
    String? taskId,
    String? subtaskId,
    String? taskAppointmentId,
    String? source,
    String? taskName,
    String? subtaskName,
    String? appointmentNotes,
    String? assigneeId,
    String? assigneeName,
    String? taskDetails,
    String? subtaskDetails,
    String? appointmentDetails,
    String? projectId,
    String? projectName,
    DateTime? createdAt,
    List<String>? taskCollaborators,
  }) {
    return DueDateTaskSubtaskAppointmentViewRow(
      dueDate: dueDate ?? this.dueDate,
      taskId: taskId ?? this.taskId,
      subtaskId: subtaskId ?? this.subtaskId,
      taskAppointmentId: taskAppointmentId ?? this.taskAppointmentId,
      source: source ?? this.source,
      taskName: taskName ?? this.taskName,
      subtaskName: subtaskName ?? this.subtaskName,
      appointmentNotes: appointmentNotes ?? this.appointmentNotes,
      assigneeId: assigneeId ?? this.assigneeId,
      assigneeName: assigneeName ?? this.assigneeName,
      taskDetails: taskDetails ?? this.taskDetails,
      subtaskDetails: subtaskDetails ?? this.subtaskDetails,
      appointmentDetails: appointmentDetails ?? this.appointmentDetails,
      projectId: projectId ?? this.projectId,
      projectName: projectName ?? this.projectName,
      createdAt: createdAt ?? this.createdAt,
      taskCollaborators: taskCollaborators ?? this.taskCollaborators,
    );
  }
}
