// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ExpenseRow {
  static const table = 'expense';

  static const field = (
    id: 'id',
    amountKrw: 'amount_krw',
    type: 'type',
    date: 'date',
    assignee: 'assignee',
    createdBy: 'created_by',
    createdAt: 'created_at',
    name: 'name',
    clinic: 'clinic',
  );

  final String id;
  final double? amountKrw;
  final String? type;
  final DateTime? date;
  final String? assignee;
  final String? createdBy;
  final DateTime createdAt;
  final String? name;
  final String? clinic;

  const ExpenseRow({
    required this.id,
    this.amountKrw,
    this.type,
    this.date,
    this.assignee,
    this.createdBy,
    required this.createdAt,
    this.name,
    this.clinic,
  });

  factory ExpenseRow.fromJson(Map<String, dynamic> json) {
    return ExpenseRow(
      id: json[field.id] as String,
      amountKrw: json[field.amountKrw] == null ? null : (json[field.amountKrw] as num?)?.toDouble(),
      type: json[field.type],
      date: json[field.date] == null ? null : DateTime.tryParse(json[field.date] ?? ''),
      assignee: json[field.assignee],
      createdBy: json[field.createdBy],
      createdAt: DateTime.parse(json[field.createdAt]),
      name: json[field.name],
      clinic: json[field.clinic],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.amountKrw: amountKrw,
      field.type: type,
      field.date: date?.toIso8601String(),
      field.assignee: assignee,
      field.createdBy: createdBy,
      field.createdAt: createdAt.toIso8601String(),
      field.name: name,
      field.clinic: clinic,
    };
  }

  ExpenseRow copyWith({
    String? id,
    double? amountKrw,
    String? type,
    DateTime? date,
    String? assignee,
    String? createdBy,
    DateTime? createdAt,
    String? name,
    String? clinic,
  }) {
    return ExpenseRow(
      id: id ?? this.id,
      amountKrw: amountKrw ?? this.amountKrw,
      type: type ?? this.type,
      date: date ?? this.date,
      assignee: assignee ?? this.assignee,
      createdBy: createdBy ?? this.createdBy,
      createdAt: createdAt ?? this.createdAt,
      name: name ?? this.name,
      clinic: clinic ?? this.clinic,
    );
  }
}
