// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class GroupRow {
  static const table = 'group';

  static const field = (
    id: 'id',
    title: 'title',
    description: 'description',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    project: 'project',
    createdBy: 'created_by',
    deletedAt: 'deleted_at',
  );

  final String id;
  final String? title;
  final String? description;
  final DateTime createdAt;
  final DateTime? updatedAt;
  final String? project;
  final String? createdBy;
  final DateTime? deletedAt;

  const GroupRow({
    required this.id,
    this.title,
    this.description,
    required this.createdAt,
    this.updatedAt,
    this.project,
    this.createdBy,
    this.deletedAt,
  });

  factory GroupRow.fromJson(Map<String, dynamic> json) {
    return GroupRow(
      id: json[field.id] as String,
      title: json[field.title],
      description: json[field.description],
      createdAt: DateTime.parse(json[field.createdAt]),
      updatedAt: json[field.updatedAt] == null ? null : DateTime.tryParse(json[field.updatedAt] ?? ''),
      project: json[field.project],
      createdBy: json[field.createdBy],
      deletedAt: json[field.deletedAt] == null ? null : DateTime.tryParse(json[field.deletedAt] ?? ''),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.title: title,
      field.description: description,
      field.createdAt: createdAt.toIso8601String(),
      field.updatedAt: updatedAt?.toIso8601String(),
      field.project: project,
      field.createdBy: createdBy,
      field.deletedAt: deletedAt?.toIso8601String(),
    };
  }

  GroupRow copyWith({
    String? id,
    String? title,
    String? description,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? project,
    String? createdBy,
    DateTime? deletedAt,
  }) {
    return GroupRow(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      project: project ?? this.project,
      createdBy: createdBy ?? this.createdBy,
      deletedAt: deletedAt ?? this.deletedAt,
    );
  }
}
