// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class NotificationRow {
  static const table = 'notification';

  static const field = (
    id: 'id',
    title: 'title',
    description: 'description',
    seen: 'seen',
    user: 'user',
    createdAt: 'created_at',
  );

  final String id;
  final String? title;
  final String? description;
  final bool? seen;
  final String? user;
  final DateTime createdAt;

  const NotificationRow({
    required this.id,
    this.title,
    this.description,
    this.seen,
    this.user,
    required this.createdAt,
  });

  factory NotificationRow.fromJson(Map<String, dynamic> json) {
    return NotificationRow(
      id: json[field.id] as String,
      title: json[field.title],
      description: json[field.description],
      seen: json[field.seen],
      user: json[field.user],
      createdAt: DateTime.parse(json[field.createdAt]),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.title: title,
      field.description: description,
      field.seen: seen,
      field.user: user,
      field.createdAt: createdAt.toIso8601String(),
    };
  }

  NotificationRow copyWith({
    String? id,
    String? title,
    String? description,
    bool? seen,
    String? user,
    DateTime? createdAt,
  }) {
    return NotificationRow(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      seen: seen ?? this.seen,
      user: user ?? this.user,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
