// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ProcedureCategoryRow {
  static const table = 'procedure_category';

  static const field = (
    id: 'id',
    name: 'name',
    createdBy: 'created_by',
    createdAt: 'created_at',
    clinic: 'clinic',
  );

  final String id;
  final String? name;
  final String? createdBy;
  final DateTime createdAt;
  final String? clinic;

  const ProcedureCategoryRow({
    required this.id,
    this.name,
    this.createdBy,
    required this.createdAt,
    this.clinic,
  });

  factory ProcedureCategoryRow.fromJson(Map<String, dynamic> json) {
    return ProcedureCategoryRow(
      id: json[field.id] as String,
      name: json[field.name],
      createdBy: json[field.createdBy],
      createdAt: DateTime.parse(json[field.createdAt]),
      clinic: json[field.clinic],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.name: name,
      field.createdBy: createdBy,
      field.createdAt: createdAt.toIso8601String(),
      field.clinic: clinic,
    };
  }

  ProcedureCategoryRow copyWith({
    String? id,
    String? name,
    String? createdBy,
    DateTime? createdAt,
    String? clinic,
  }) {
    return ProcedureCategoryRow(
      id: id ?? this.id,
      name: name ?? this.name,
      createdBy: createdBy ?? this.createdBy,
      createdAt: createdAt ?? this.createdAt,
      clinic: clinic ?? this.clinic,
    );
  }
}
