// Generated by row_row_row tool
// Auto-generated file. Do not modify.
import 'dart:convert';

class ProjectWithMembersRow {
  static const table = 'project_with_members';

  static const field = (
    id: 'id',
    title: 'title',
    createdBy: 'created_by',
    createdAt: 'created_at',
    status: 'status',
    isClinic: 'is_clinic',
    description: 'description',
    canChooseOtherClinic: 'can_choose_other_clinic',
    asanaProjectGid: 'asana_project_gid',
    pinOrder: 'pin_order',
    area: 'area',
    numberOfMembers: 'number_of_members',
    memberIds: 'member_ids',
    members: 'members',
  );

  final String? id;
  final String? title;
  final String? createdBy;
  final DateTime? createdAt;
  final String? status;
  final bool? isClinic;
  final String? description;
  final bool? canChooseOtherClinic;
  final String? asanaProjectGid;
  final DateTime? pinOrder;
  final String? area;
  final int? numberOfMembers;
  final List<String>? memberIds;
  final Map<dynamic, dynamic>? members;

  const ProjectWithMembersRow({
    this.id,
    this.title,
    this.createdBy,
    this.createdAt,
    this.status,
    this.isClinic,
    this.description,
    this.canChooseOtherClinic,
    this.asanaProjectGid,
    this.pinOrder,
    this.area,
    this.numberOfMembers,
    this.memberIds,
    this.members,
  });

  factory ProjectWithMembersRow.fromJson(Map<String, dynamic> json) {
    return ProjectWithMembersRow(
      id: json[field.id],
      title: json[field.title],
      createdBy: json[field.createdBy],
      createdAt: json[field.createdAt] == null ? null : DateTime.tryParse(json[field.createdAt] ?? ''),
      status: json[field.status],
      isClinic: json[field.isClinic],
      description: json[field.description],
      canChooseOtherClinic: json[field.canChooseOtherClinic],
      asanaProjectGid: json[field.asanaProjectGid],
      pinOrder: json[field.pinOrder] == null ? null : DateTime.tryParse(json[field.pinOrder] ?? ''),
      area: json[field.area],
      numberOfMembers: json[field.numberOfMembers] == null ? null : (json[field.numberOfMembers] as num?)?.toInt(),
      memberIds: json[field.memberIds] == null ? null : List<String>.from(json[field.memberIds]),
      members: json[field.members] == null ? null : (json[field.members] is String ? jsonDecode(json[field.members]) : Map.from(json[field.members])),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.title: title,
      field.createdBy: createdBy,
      field.createdAt: createdAt?.toIso8601String(),
      field.status: status,
      field.isClinic: isClinic,
      field.description: description,
      field.canChooseOtherClinic: canChooseOtherClinic,
      field.asanaProjectGid: asanaProjectGid,
      field.pinOrder: pinOrder?.toIso8601String(),
      field.area: area,
      field.numberOfMembers: numberOfMembers,
      field.memberIds: memberIds,
      field.members: members,
    };
  }

  ProjectWithMembersRow copyWith({
    String? id,
    String? title,
    String? createdBy,
    DateTime? createdAt,
    String? status,
    bool? isClinic,
    String? description,
    bool? canChooseOtherClinic,
    String? asanaProjectGid,
    DateTime? pinOrder,
    String? area,
    int? numberOfMembers,
    List<String>? memberIds,
    Map<dynamic, dynamic>? members,
  }) {
    return ProjectWithMembersRow(
      id: id ?? this.id,
      title: title ?? this.title,
      createdBy: createdBy ?? this.createdBy,
      createdAt: createdAt ?? this.createdAt,
      status: status ?? this.status,
      isClinic: isClinic ?? this.isClinic,
      description: description ?? this.description,
      canChooseOtherClinic: canChooseOtherClinic ?? this.canChooseOtherClinic,
      asanaProjectGid: asanaProjectGid ?? this.asanaProjectGid,
      pinOrder: pinOrder ?? this.pinOrder,
      area: area ?? this.area,
      numberOfMembers: numberOfMembers ?? this.numberOfMembers,
      memberIds: memberIds ?? this.memberIds,
      members: members ?? this.members,
    );
  }
}
