// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class ProjectMemberRow {
  static const table = 'project_member';

  static const field = (
    id: 'id',
    createdAt: 'created_at',
    assignedBy: 'assigned_by',
    user: 'user',
    project: 'project',
    addedBySystem: 'added_by_system',
  );

  final String id;
  final DateTime createdAt;
  final String? assignedBy;
  final String? user;
  final String? project;
  final bool addedBySystem;

  const ProjectMemberRow({
    required this.id,
    required this.createdAt,
    this.assignedBy,
    this.user,
    this.project,
    required this.addedBySystem,
  });

  factory ProjectMemberRow.fromJson(Map<String, dynamic> json) {
    return ProjectMemberRow(
      id: json[field.id] as String,
      createdAt: DateTime.parse(json[field.createdAt]),
      assignedBy: json[field.assignedBy],
      user: json[field.user],
      project: json[field.project],
      addedBySystem: json[field.addedBySystem] as bool,
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.createdAt: createdAt.toIso8601String(),
      field.assignedBy: assignedBy,
      field.user: user,
      field.project: project,
      field.addedBySystem: addedBySystem,
    };
  }

  ProjectMemberRow copyWith({
    String? id,
    DateTime? createdAt,
    String? assignedBy,
    String? user,
    String? project,
    bool? addedBySystem,
  }) {
    return ProjectMemberRow(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      assignedBy: assignedBy ?? this.assignedBy,
      user: user ?? this.user,
      project: project ?? this.project,
      addedBySystem: addedBySystem ?? this.addedBySystem,
    );
  }
}
