// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class RefundReasonRow {
  static const table = 'refund_reason';

  static const field = (
    id: 'id',
    reason: 'reason',
    createdAt: 'created_at',
    createdBy: 'created_by',
    isActive: 'is_active',
  );

  final String id;
  final String? reason;
  final DateTime createdAt;
  final String? createdBy;
  final bool isActive;

  const RefundReasonRow({
    required this.id,
    this.reason,
    required this.createdAt,
    this.createdBy,
    required this.isActive,
  });

  factory RefundReasonRow.fromJson(Map<String, dynamic> json) {
    return RefundReasonRow(
      id: json[field.id] as String,
      reason: json[field.reason],
      createdAt: DateTime.parse(json[field.createdAt]),
      createdBy: json[field.createdBy],
      isActive: json[field.isActive] as bool,
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.reason: reason,
      field.createdAt: createdAt.toIso8601String(),
      field.createdBy: createdBy,
      field.isActive: isActive,
    };
  }

  RefundReasonRow copyWith({
    String? id,
    String? reason,
    DateTime? createdAt,
    String? createdBy,
    bool? isActive,
  }) {
    return RefundReasonRow(
      id: id ?? this.id,
      reason: reason ?? this.reason,
      createdAt: createdAt ?? this.createdAt,
      createdBy: createdBy ?? this.createdBy,
      isActive: isActive ?? this.isActive,
    );
  }
}
