// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class SectionsFromAsanaTempRow {
  static const table = 'sections_from_asana_temp';

  static const field = (
    id: 'id',
    gid: 'gid',
    createdAt: 'created_at',
    projectGid: 'project_gid',
    sysCreatedAt: 'sys_created_at',
    name: 'name',
    order: 'order',
    statusRef: 'status_ref',
  );

  final String id;
  final String? gid;
  final DateTime? createdAt;
  final String? projectGid;
  final DateTime sysCreatedAt;
  final String? name;
  final int? order;
  final String? statusRef;

  const SectionsFromAsanaTempRow({
    required this.id,
    this.gid,
    this.createdAt,
    this.projectGid,
    required this.sysCreatedAt,
    this.name,
    this.order,
    this.statusRef,
  });

  factory SectionsFromAsanaTempRow.fromJson(Map<String, dynamic> json) {
    return SectionsFromAsanaTempRow(
      id: json[field.id] as String,
      gid: json[field.gid],
      createdAt: json[field.createdAt] == null ? null : DateTime.tryParse(json[field.createdAt] ?? ''),
      projectGid: json[field.projectGid],
      sysCreatedAt: DateTime.parse(json[field.sysCreatedAt]),
      name: json[field.name],
      order: json[field.order] == null ? null : (json[field.order] as num?)?.toInt(),
      statusRef: json[field.statusRef],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.gid: gid,
      field.createdAt: createdAt?.toIso8601String(),
      field.projectGid: projectGid,
      field.sysCreatedAt: sysCreatedAt.toIso8601String(),
      field.name: name,
      field.order: order,
      field.statusRef: statusRef,
    };
  }

  SectionsFromAsanaTempRow copyWith({
    String? id,
    String? gid,
    DateTime? createdAt,
    String? projectGid,
    DateTime? sysCreatedAt,
    String? name,
    int? order,
    String? statusRef,
  }) {
    return SectionsFromAsanaTempRow(
      id: id ?? this.id,
      gid: gid ?? this.gid,
      createdAt: createdAt ?? this.createdAt,
      projectGid: projectGid ?? this.projectGid,
      sysCreatedAt: sysCreatedAt ?? this.sysCreatedAt,
      name: name ?? this.name,
      order: order ?? this.order,
      statusRef: statusRef ?? this.statusRef,
    );
  }
}
