// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class SubtaskAssigneeNameViewRow {
  static const table = 'subtask_assignee_name_view';

  static const field = (
    id: 'id',
    createdAt: 'created_at',
    assignee: 'assignee',
    assignedBy: 'assigned_by',
    subtask: 'subtask',
    assigneeName: 'assignee_name',
    profileImage: 'profile_image',
    assignedByName: 'assigned_by_name',
  );

  final String? id;
  final DateTime? createdAt;
  final String? assignee;
  final String? assignedBy;
  final String? subtask;
  final String? assigneeName;
  final String? profileImage;
  final String? assignedByName;

  const SubtaskAssigneeNameViewRow({
    this.id,
    this.createdAt,
    this.assignee,
    this.assignedBy,
    this.subtask,
    this.assigneeName,
    this.profileImage,
    this.assignedByName,
  });

  factory SubtaskAssigneeNameViewRow.fromJson(Map<String, dynamic> json) {
    return SubtaskAssigneeNameViewRow(
      id: json[field.id],
      createdAt: json[field.createdAt] == null ? null : DateTime.tryParse(json[field.createdAt] ?? ''),
      assignee: json[field.assignee],
      assignedBy: json[field.assignedBy],
      subtask: json[field.subtask],
      assigneeName: json[field.assigneeName],
      profileImage: json[field.profileImage],
      assignedByName: json[field.assignedByName],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.createdAt: createdAt?.toIso8601String(),
      field.assignee: assignee,
      field.assignedBy: assignedBy,
      field.subtask: subtask,
      field.assigneeName: assigneeName,
      field.profileImage: profileImage,
      field.assignedByName: assignedByName,
    };
  }

  SubtaskAssigneeNameViewRow copyWith({
    String? id,
    DateTime? createdAt,
    String? assignee,
    String? assignedBy,
    String? subtask,
    String? assigneeName,
    String? profileImage,
    String? assignedByName,
  }) {
    return SubtaskAssigneeNameViewRow(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      assignee: assignee ?? this.assignee,
      assignedBy: assignedBy ?? this.assignedBy,
      subtask: subtask ?? this.subtask,
      assigneeName: assigneeName ?? this.assigneeName,
      profileImage: profileImage ?? this.profileImage,
      assignedByName: assignedByName ?? this.assignedByName,
    );
  }
}
