// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class SubtaskRow {
  static const table = 'subtask';

  static const field = (
    id: 'id',
    name: 'name',
    description: 'description',
    dueDate: 'due_date',
    createdAt: 'created_at',
    task: 'task',
    gid: 'gid',
    rawDescription: 'raw_description',
    asanaAttachmentProcessedOn: 'asana_attachment_processed_on',
    completedAt: 'completed_at',
  );

  final String id;
  final String? name;
  final String? description;
  final DateTime? dueDate;
  final DateTime createdAt;
  final String? task;
  final String? gid;
  final String? rawDescription;
  final DateTime? asanaAttachmentProcessedOn;
  final DateTime? completedAt;

  const SubtaskRow({
    required this.id,
    this.name,
    this.description,
    this.dueDate,
    required this.createdAt,
    this.task,
    this.gid,
    this.rawDescription,
    this.asanaAttachmentProcessedOn,
    this.completedAt,
  });

  factory SubtaskRow.fromJson(Map<String, dynamic> json) {
    return SubtaskRow(
      id: json[field.id] as String,
      name: json[field.name],
      description: json[field.description],
      dueDate: json[field.dueDate] == null ? null : DateTime.tryParse(json[field.dueDate] ?? ''),
      createdAt: DateTime.parse(json[field.createdAt]),
      task: json[field.task],
      gid: json[field.gid],
      rawDescription: json[field.rawDescription],
      asanaAttachmentProcessedOn: json[field.asanaAttachmentProcessedOn] == null ? null : DateTime.tryParse(json[field.asanaAttachmentProcessedOn] ?? ''),
      completedAt: json[field.completedAt] == null ? null : DateTime.tryParse(json[field.completedAt] ?? ''),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.name: name,
      field.description: description,
      field.dueDate: dueDate?.toIso8601String(),
      field.createdAt: createdAt.toIso8601String(),
      field.task: task,
      field.gid: gid,
      field.rawDescription: rawDescription,
      field.asanaAttachmentProcessedOn: asanaAttachmentProcessedOn?.toIso8601String(),
      field.completedAt: completedAt?.toIso8601String(),
    };
  }

  SubtaskRow copyWith({
    String? id,
    String? name,
    String? description,
    DateTime? dueDate,
    DateTime? createdAt,
    String? task,
    String? gid,
    String? rawDescription,
    DateTime? asanaAttachmentProcessedOn,
    DateTime? completedAt,
  }) {
    return SubtaskRow(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      dueDate: dueDate ?? this.dueDate,
      createdAt: createdAt ?? this.createdAt,
      task: task ?? this.task,
      gid: gid ?? this.gid,
      rawDescription: rawDescription ?? this.rawDescription,
      asanaAttachmentProcessedOn: asanaAttachmentProcessedOn ?? this.asanaAttachmentProcessedOn,
      completedAt: completedAt ?? this.completedAt,
    );
  }
}
