// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskClinicDepositSumRow {
  static const table = 'task_clinic_deposit_sum';

  static const field = (
    taskId: 'task_id',
    clinic: 'clinic',
    depositSum: 'deposit_sum',
  );

  final String? taskId;
  final String? clinic;
  final double? depositSum;

  const TaskClinicDepositSumRow({
    this.taskId,
    this.clinic,
    this.depositSum,
  });

  factory TaskClinicDepositSumRow.fromJson(Map<String, dynamic> json) {
    return TaskClinicDepositSumRow(
      taskId: json[field.taskId],
      clinic: json[field.clinic],
      depositSum: json[field.depositSum] == null ? null : (json[field.depositSum] as num?)?.toDouble(),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.taskId: taskId,
      field.clinic: clinic,
      field.depositSum: depositSum,
    };
  }

  TaskClinicDepositSumRow copyWith({
    String? taskId,
    String? clinic,
    double? depositSum,
  }) {
    return TaskClinicDepositSumRow(
      taskId: taskId ?? this.taskId,
      clinic: clinic ?? this.clinic,
      depositSum: depositSum ?? this.depositSum,
    );
  }
}
