// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskCommentRow {
  static const table = 'task_comment';

  static const field = (
    id: 'id',
    content: 'content',
    createdAt: 'created_at',
    createdBy: 'created_by',
    task: 'task',
  );

  final String id;
  final String? content;
  final DateTime createdAt;
  final String? createdBy;
  final String? task;

  const TaskCommentRow({
    required this.id,
    this.content,
    required this.createdAt,
    this.createdBy,
    this.task,
  });

  factory TaskCommentRow.fromJson(Map<String, dynamic> json) {
    return TaskCommentRow(
      id: json[field.id] as String,
      content: json[field.content],
      createdAt: DateTime.parse(json[field.createdAt]),
      createdBy: json[field.createdBy],
      task: json[field.task],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.content: content,
      field.createdAt: createdAt.toIso8601String(),
      field.createdBy: createdBy,
      field.task: task,
    };
  }

  TaskCommentRow copyWith({
    String? id,
    String? content,
    DateTime? createdAt,
    String? createdBy,
    String? task,
  }) {
    return TaskCommentRow(
      id: id ?? this.id,
      content: content ?? this.content,
      createdAt: createdAt ?? this.createdAt,
      createdBy: createdBy ?? this.createdBy,
      task: task ?? this.task,
    );
  }
}
