// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskAppointmentProcedureSummaryCsvRow {
  static const table = 'task_appointment_procedure_summary_csv';

  static const field = (
    taskId: 'task_id',
    appointmentId: 'appointment_id',
    customerName: 'customer_name',
    scheduledDateTimeKst: 'scheduled_date_time_kst',
    generalDeposit: 'general_deposit',
    generalDiscountRate: 'general_discount_rate',
    generalDiscountAmount: 'general_discount_amount',
    generalRefund: 'general_refund',
    procedureId: 'procedure_id',
    procedureName: 'procedure_name',
    offeredProcedurePrice: 'offered_procedure_price',
    finalProcedurePrice: 'final_procedure_price',
    finalCommission: 'final_commission',
    procedureSpecificDiscountRate: 'procedure_specific_discount_rate',
    procedureSpecificDiscountAmount: 'procedure_specific_discount_amount',
    procedureSpecificRefundAmount: 'procedure_specific_refund_amount',
    procedureSpecificExpense: 'procedure_specific_expense',
  );

  final String? taskId;
  final String? appointmentId;
  final String? customerName;
  final DateTime? scheduledDateTimeKst;
  final double? generalDeposit;
  final double? generalDiscountRate;
  final double? generalDiscountAmount;
  final double? generalRefund;
  final String? procedureId;
  final String? procedureName;
  final double? offeredProcedurePrice;
  final double? finalProcedurePrice;
  final double? finalCommission;
  final double? procedureSpecificDiscountRate;
  final double? procedureSpecificDiscountAmount;
  final double? procedureSpecificRefundAmount;
  final double? procedureSpecificExpense;

  const TaskAppointmentProcedureSummaryCsvRow({
    this.taskId,
    this.appointmentId,
    this.customerName,
    this.scheduledDateTimeKst,
    this.generalDeposit,
    this.generalDiscountRate,
    this.generalDiscountAmount,
    this.generalRefund,
    this.procedureId,
    this.procedureName,
    this.offeredProcedurePrice,
    this.finalProcedurePrice,
    this.finalCommission,
    this.procedureSpecificDiscountRate,
    this.procedureSpecificDiscountAmount,
    this.procedureSpecificRefundAmount,
    this.procedureSpecificExpense,
  });

  factory TaskAppointmentProcedureSummaryCsvRow.fromJson(Map<String, dynamic> json) {
    return TaskAppointmentProcedureSummaryCsvRow(
      taskId: json[field.taskId],
      appointmentId: json[field.appointmentId],
      customerName: json[field.customerName],
      scheduledDateTimeKst: json[field.scheduledDateTimeKst] == null ? null : DateTime.tryParse(json[field.scheduledDateTimeKst] ?? ''),
      generalDeposit: json[field.generalDeposit] == null ? null : (json[field.generalDeposit] as num?)?.toDouble(),
      generalDiscountRate: json[field.generalDiscountRate] == null ? null : (json[field.generalDiscountRate] as num?)?.toDouble(),
      generalDiscountAmount: json[field.generalDiscountAmount] == null ? null : (json[field.generalDiscountAmount] as num?)?.toDouble(),
      generalRefund: json[field.generalRefund] == null ? null : (json[field.generalRefund] as num?)?.toDouble(),
      procedureId: json[field.procedureId],
      procedureName: json[field.procedureName],
      offeredProcedurePrice: json[field.offeredProcedurePrice] == null ? null : (json[field.offeredProcedurePrice] as num?)?.toDouble(),
      finalProcedurePrice: json[field.finalProcedurePrice] == null ? null : (json[field.finalProcedurePrice] as num?)?.toDouble(),
      finalCommission: json[field.finalCommission] == null ? null : (json[field.finalCommission] as num?)?.toDouble(),
      procedureSpecificDiscountRate: json[field.procedureSpecificDiscountRate] == null ? null : (json[field.procedureSpecificDiscountRate] as num?)?.toDouble(),
      procedureSpecificDiscountAmount: json[field.procedureSpecificDiscountAmount] == null ? null : (json[field.procedureSpecificDiscountAmount] as num?)?.toDouble(),
      procedureSpecificRefundAmount: json[field.procedureSpecificRefundAmount] == null ? null : (json[field.procedureSpecificRefundAmount] as num?)?.toDouble(),
      procedureSpecificExpense: json[field.procedureSpecificExpense] == null ? null : (json[field.procedureSpecificExpense] as num?)?.toDouble(),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.taskId: taskId,
      field.appointmentId: appointmentId,
      field.customerName: customerName,
      field.scheduledDateTimeKst: scheduledDateTimeKst?.toIso8601String(),
      field.generalDeposit: generalDeposit,
      field.generalDiscountRate: generalDiscountRate,
      field.generalDiscountAmount: generalDiscountAmount,
      field.generalRefund: generalRefund,
      field.procedureId: procedureId,
      field.procedureName: procedureName,
      field.offeredProcedurePrice: offeredProcedurePrice,
      field.finalProcedurePrice: finalProcedurePrice,
      field.finalCommission: finalCommission,
      field.procedureSpecificDiscountRate: procedureSpecificDiscountRate,
      field.procedureSpecificDiscountAmount: procedureSpecificDiscountAmount,
      field.procedureSpecificRefundAmount: procedureSpecificRefundAmount,
      field.procedureSpecificExpense: procedureSpecificExpense,
    };
  }

  TaskAppointmentProcedureSummaryCsvRow copyWith({
    String? taskId,
    String? appointmentId,
    String? customerName,
    DateTime? scheduledDateTimeKst,
    double? generalDeposit,
    double? generalDiscountRate,
    double? generalDiscountAmount,
    double? generalRefund,
    String? procedureId,
    String? procedureName,
    double? offeredProcedurePrice,
    double? finalProcedurePrice,
    double? finalCommission,
    double? procedureSpecificDiscountRate,
    double? procedureSpecificDiscountAmount,
    double? procedureSpecificRefundAmount,
    double? procedureSpecificExpense,
  }) {
    return TaskAppointmentProcedureSummaryCsvRow(
      taskId: taskId ?? this.taskId,
      appointmentId: appointmentId ?? this.appointmentId,
      customerName: customerName ?? this.customerName,
      scheduledDateTimeKst: scheduledDateTimeKst ?? this.scheduledDateTimeKst,
      generalDeposit: generalDeposit ?? this.generalDeposit,
      generalDiscountRate: generalDiscountRate ?? this.generalDiscountRate,
      generalDiscountAmount: generalDiscountAmount ?? this.generalDiscountAmount,
      generalRefund: generalRefund ?? this.generalRefund,
      procedureId: procedureId ?? this.procedureId,
      procedureName: procedureName ?? this.procedureName,
      offeredProcedurePrice: offeredProcedurePrice ?? this.offeredProcedurePrice,
      finalProcedurePrice: finalProcedurePrice ?? this.finalProcedurePrice,
      finalCommission: finalCommission ?? this.finalCommission,
      procedureSpecificDiscountRate: procedureSpecificDiscountRate ?? this.procedureSpecificDiscountRate,
      procedureSpecificDiscountAmount: procedureSpecificDiscountAmount ?? this.procedureSpecificDiscountAmount,
      procedureSpecificRefundAmount: procedureSpecificRefundAmount ?? this.procedureSpecificRefundAmount,
      procedureSpecificExpense: procedureSpecificExpense ?? this.procedureSpecificExpense,
    );
  }
}
