// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskCustomerProcedureClinicRow {
  static const table = 'task_customer_procedure_clinic';

  static const field = (
    task: 'task',
    clinic: 'clinic',
  );

  final String? task;
  final String? clinic;

  const TaskCustomerProcedureClinicRow({
    this.task,
    this.clinic,
  });

  factory TaskCustomerProcedureClinicRow.fromJson(Map<String, dynamic> json) {
    return TaskCustomerProcedureClinicRow(
      task: json[field.task],
      clinic: json[field.clinic],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.task: task,
      field.clinic: clinic,
    };
  }

  TaskCustomerProcedureClinicRow copyWith({
    String? task,
    String? clinic,
  }) {
    return TaskCustomerProcedureClinicRow(
      task: task ?? this.task,
      clinic: clinic ?? this.clinic,
    );
  }
}
