// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskActivityRow {
  static const table = 'task_activity';

  static const field = (
    id: 'id',
    description: 'description',
    user: 'user',
    createdAt: 'created_at',
    task: 'task',
  );

  final String id;
  final String? description;
  final String? user;
  final DateTime createdAt;
  final String? task;

  const TaskActivityRow({
    required this.id,
    this.description,
    this.user,
    required this.createdAt,
    this.task,
  });

  factory TaskActivityRow.fromJson(Map<String, dynamic> json) {
    return TaskActivityRow(
      id: json[field.id] as String,
      description: json[field.description],
      user: json[field.user],
      createdAt: DateTime.parse(json[field.createdAt]),
      task: json[field.task],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.description: description,
      field.user: user,
      field.createdAt: createdAt.toIso8601String(),
      field.task: task,
    };
  }

  TaskActivityRow copyWith({
    String? id,
    String? description,
    String? user,
    DateTime? createdAt,
    String? task,
  }) {
    return TaskActivityRow(
      id: id ?? this.id,
      description: description ?? this.description,
      user: user ?? this.user,
      createdAt: createdAt ?? this.createdAt,
      task: task ?? this.task,
    );
  }
}
