// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskDepositRefundTotalRow {
  static const table = 'task_deposit_refund_total';

  static const field = (
    taskId: 'task_id',
    totalDeposit: 'total_deposit',
    totalRefund: 'total_refund',
  );

  final String? taskId;
  final double? totalDeposit;
  final double? totalRefund;

  const TaskDepositRefundTotalRow({
    this.taskId,
    this.totalDeposit,
    this.totalRefund,
  });

  factory TaskDepositRefundTotalRow.fromJson(Map<String, dynamic> json) {
    return TaskDepositRefundTotalRow(
      taskId: json[field.taskId],
      totalDeposit: json[field.totalDeposit] == null ? null : (json[field.totalDeposit] as num?)?.toDouble(),
      totalRefund: json[field.totalRefund] == null ? null : (json[field.totalRefund] as num?)?.toDouble(),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.taskId: taskId,
      field.totalDeposit: totalDeposit,
      field.totalRefund: totalRefund,
    };
  }

  TaskDepositRefundTotalRow copyWith({
    String? taskId,
    double? totalDeposit,
    double? totalRefund,
  }) {
    return TaskDepositRefundTotalRow(
      taskId: taskId ?? this.taskId,
      totalDeposit: totalDeposit ?? this.totalDeposit,
      totalRefund: totalRefund ?? this.totalRefund,
    );
  }
}
