// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskAppointmentProcedureSpecificExpenseRow {
  static const table = 'task_appointment_procedure_specific_expense';

  static const field = (
    id: 'id',
    appointmentProcedure: 'appointment_procedure',
    name: 'name',
    details: 'details',
    amount: 'amount',
    addedBy: 'added_by',
    createdAt: 'created_at',
    date: 'date',
  );

  final String id;
  final String appointmentProcedure;
  final String? name;
  final String? details;
  final double amount;
  final String? addedBy;
  final DateTime createdAt;
  final DateTime date;

  const TaskAppointmentProcedureSpecificExpenseRow({
    required this.id,
    required this.appointmentProcedure,
    this.name,
    this.details,
    required this.amount,
    this.addedBy,
    required this.createdAt,
    required this.date,
  });

  factory TaskAppointmentProcedureSpecificExpenseRow.fromJson(Map<String, dynamic> json) {
    return TaskAppointmentProcedureSpecificExpenseRow(
      id: json[field.id] as String,
      appointmentProcedure: json[field.appointmentProcedure] as String,
      name: json[field.name],
      details: json[field.details],
      amount: (json[field.amount] as num).toDouble(),
      addedBy: json[field.addedBy],
      createdAt: DateTime.parse(json[field.createdAt]),
      date: DateTime.parse(json[field.date]),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.appointmentProcedure: appointmentProcedure,
      field.name: name,
      field.details: details,
      field.amount: amount,
      field.addedBy: addedBy,
      field.createdAt: createdAt.toIso8601String(),
      field.date: date.toIso8601String(),
    };
  }

  TaskAppointmentProcedureSpecificExpenseRow copyWith({
    String? id,
    String? appointmentProcedure,
    String? name,
    String? details,
    double? amount,
    String? addedBy,
    DateTime? createdAt,
    DateTime? date,
  }) {
    return TaskAppointmentProcedureSpecificExpenseRow(
      id: id ?? this.id,
      appointmentProcedure: appointmentProcedure ?? this.appointmentProcedure,
      name: name ?? this.name,
      details: details ?? this.details,
      amount: amount ?? this.amount,
      addedBy: addedBy ?? this.addedBy,
      createdAt: createdAt ?? this.createdAt,
      date: date ?? this.date,
    );
  }
}
