// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskClinicDiscountRow {
  static const table = 'task_clinic_discount';

  static const field = (
    id: 'id',
    createdAt: 'created_at',
    rate: 'rate',
    amount: 'amount',
    clinic: 'clinic',
    task: 'task',
  );

  final String id;
  final DateTime createdAt;
  final double? rate;
  final double? amount;
  final String? clinic;
  final String? task;

  const TaskClinicDiscountRow({
    required this.id,
    required this.createdAt,
    this.rate,
    this.amount,
    this.clinic,
    this.task,
  });

  factory TaskClinicDiscountRow.fromJson(Map<String, dynamic> json) {
    return TaskClinicDiscountRow(
      id: json[field.id] as String,
      createdAt: DateTime.parse(json[field.createdAt]),
      rate: json[field.rate] == null ? null : (json[field.rate] as num?)?.toDouble(),
      amount: json[field.amount] == null ? null : (json[field.amount] as num?)?.toDouble(),
      clinic: json[field.clinic],
      task: json[field.task],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.createdAt: createdAt.toIso8601String(),
      field.rate: rate,
      field.amount: amount,
      field.clinic: clinic,
      field.task: task,
    };
  }

  TaskClinicDiscountRow copyWith({
    String? id,
    DateTime? createdAt,
    double? rate,
    double? amount,
    String? clinic,
    String? task,
  }) {
    return TaskClinicDiscountRow(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      rate: rate ?? this.rate,
      amount: amount ?? this.amount,
      clinic: clinic ?? this.clinic,
      task: task ?? this.task,
    );
  }
}
