// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TaskClinicDepositRow {
  static const table = 'task_clinic_deposit';

  static const field = (
    id: 'id',
    amount: 'amount',
    task: 'task',
    clinic: 'clinic',
    date: 'date',
    createdAt: 'created_at',
    addedBy: 'added_by',
  );

  final String id;
  final double amount;
  final String? task;
  final String? clinic;
  final DateTime date;
  final DateTime createdAt;
  final String? addedBy;

  const TaskClinicDepositRow({
    required this.id,
    required this.amount,
    this.task,
    this.clinic,
    required this.date,
    required this.createdAt,
    this.addedBy,
  });

  factory TaskClinicDepositRow.fromJson(Map<String, dynamic> json) {
    return TaskClinicDepositRow(
      id: json[field.id] as String,
      amount: (json[field.amount] as num).toDouble(),
      task: json[field.task],
      clinic: json[field.clinic],
      date: DateTime.parse(json[field.date]),
      createdAt: DateTime.parse(json[field.createdAt]),
      addedBy: json[field.addedBy],
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.amount: amount,
      field.task: task,
      field.clinic: clinic,
      field.date: date.toIso8601String(),
      field.createdAt: createdAt.toIso8601String(),
      field.addedBy: addedBy,
    };
  }

  TaskClinicDepositRow copyWith({
    String? id,
    double? amount,
    String? task,
    String? clinic,
    DateTime? date,
    DateTime? createdAt,
    String? addedBy,
  }) {
    return TaskClinicDepositRow(
      id: id ?? this.id,
      amount: amount ?? this.amount,
      task: task ?? this.task,
      clinic: clinic ?? this.clinic,
      date: date ?? this.date,
      createdAt: createdAt ?? this.createdAt,
      addedBy: addedBy ?? this.addedBy,
    );
  }
}
