// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class TermsAndConditionRow {
  static const table = 'terms_and_condition';

  static const field = (
    id: 'id',
    createdAt: 'created_at',
    terms: 'terms',
  );

  final String id;
  final DateTime createdAt;
  final String terms;

  const TermsAndConditionRow({
    required this.id,
    required this.createdAt,
    required this.terms,
  });

  factory TermsAndConditionRow.fromJson(Map<String, dynamic> json) {
    return TermsAndConditionRow(
      id: json[field.id] as String,
      createdAt: DateTime.parse(json[field.createdAt]),
      terms: json[field.terms] as String,
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.createdAt: createdAt.toIso8601String(),
      field.terms: terms,
    };
  }

  TermsAndConditionRow copyWith({
    String? id,
    DateTime? createdAt,
    String? terms,
  }) {
    return TermsAndConditionRow(
      id: id ?? this.id,
      createdAt: createdAt ?? this.createdAt,
      terms: terms ?? this.terms,
    );
  }
}
