// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class UserBanDataRow {
  static const table = 'user_ban_data';

  static const field = (
    id: 'id',
    isBanned: 'is_banned',
    bannedUntil: 'banned_until',
  );

  final String? id;
  final bool? isBanned;
  final DateTime? bannedUntil;

  const UserBanDataRow({
    this.id,
    this.isBanned,
    this.bannedUntil,
  });

  factory UserBanDataRow.fromJson(Map<String, dynamic> json) {
    return UserBanDataRow(
      id: json[field.id],
      isBanned: json[field.isBanned],
      bannedUntil: json[field.bannedUntil] == null ? null : DateTime.tryParse(json[field.bannedUntil] ?? ''),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.isBanned: isBanned,
      field.bannedUntil: bannedUntil?.toIso8601String(),
    };
  }

  UserBanDataRow copyWith({
    String? id,
    bool? isBanned,
    DateTime? bannedUntil,
  }) {
    return UserBanDataRow(
      id: id ?? this.id,
      isBanned: isBanned ?? this.isBanned,
      bannedUntil: bannedUntil ?? this.bannedUntil,
    );
  }
}
