// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class UsersTemporaryFromAsanaRow {
  static const table = 'users_temporary_from_asana';

  static const field = (
    id: 'id',
    gid: 'gid',
    email: 'email',
    name: 'name',
    userId: 'user_id',
    photo: 'photo',
    createdAt: 'created_at',
  );

  final String id;
  final String? gid;
  final String? email;
  final String? name;
  final String? userId;
  final String? photo;
  final DateTime createdAt;

  const UsersTemporaryFromAsanaRow({
    required this.id,
    this.gid,
    this.email,
    this.name,
    this.userId,
    this.photo,
    required this.createdAt,
  });

  factory UsersTemporaryFromAsanaRow.fromJson(Map<String, dynamic> json) {
    return UsersTemporaryFromAsanaRow(
      id: json[field.id] as String,
      gid: json[field.gid],
      email: json[field.email],
      name: json[field.name],
      userId: json[field.userId],
      photo: json[field.photo],
      createdAt: DateTime.parse(json[field.createdAt]),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.gid: gid,
      field.email: email,
      field.name: name,
      field.userId: userId,
      field.photo: photo,
      field.createdAt: createdAt.toIso8601String(),
    };
  }

  UsersTemporaryFromAsanaRow copyWith({
    String? id,
    String? gid,
    String? email,
    String? name,
    String? userId,
    String? photo,
    DateTime? createdAt,
  }) {
    return UsersTemporaryFromAsanaRow(
      id: id ?? this.id,
      gid: gid ?? this.gid,
      email: email ?? this.email,
      name: name ?? this.name,
      userId: userId ?? this.userId,
      photo: photo ?? this.photo,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
