// Generated by row_row_row tool
// Auto-generated file. Do not modify.
class UserGroupMemberRow {
  static const table = 'user_group_member';

  static const field = (
    id: 'id',
    member: 'member',
    group: 'group',
    addedBy: 'added_by',
    createdAt: 'created_at',
  );

  final String id;
  final String? member;
  final String? group;
  final String? addedBy;
  final DateTime createdAt;

  const UserGroupMemberRow({
    required this.id,
    this.member,
    this.group,
    this.addedBy,
    required this.createdAt,
  });

  factory UserGroupMemberRow.fromJson(Map<String, dynamic> json) {
    return UserGroupMemberRow(
      id: json[field.id] as String,
      member: json[field.member],
      group: json[field.group],
      addedBy: json[field.addedBy],
      createdAt: DateTime.parse(json[field.createdAt]),
    );
  }
  Map<String, dynamic> toJson() {
    return {
      field.id: id,
      field.member: member,
      field.group: group,
      field.addedBy: addedBy,
      field.createdAt: createdAt.toIso8601String(),
    };
  }

  UserGroupMemberRow copyWith({
    String? id,
    String? member,
    String? group,
    String? addedBy,
    DateTime? createdAt,
  }) {
    return UserGroupMemberRow(
      id: id ?? this.id,
      member: member ?? this.member,
      group: group ?? this.group,
      addedBy: addedBy ?? this.addedBy,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
